FROM node:gallium-bullseye-slim AS builder
WORKDIR /app/node-proxy
COPY ./ /app
RUN pwd
RUN npm i
RUN npm run build
RUN ls /app/node-proxy/dist


FROM node:gallium-alpine
WORKDIR /root/
COPY --from=builder /app/node-proxy/ncc ./
RUN rm -rf /etc/localtime && ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
EXPOSE 5344
ENTRYPOINT ["node", "index.js"]
